# 注意开源时这个文件不要提交、或者不要填真实配置
spring:
  # DataSource Config
  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    url: jdbc:mysql://110.40.211.224:3306/interest?useSSL=false
    username: root
    password: 419520
  # session 失效时间
  session:
    timeout: 86400
server:
  address: 0.0.0.0
